apiVersion: apps/v1
kind: Deployment
metadata:
  name: trial-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trial
  template:
    metadata:
      labels:
        app: trial
    spec:
      containers:
      - name: trial
        # We advise you to build, push and use your own image, instead of using instructor's image.
        image: haithanh86/trial:v1
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: trial
spec:
  selector:
    app: trial
  ports:
    - port: 8082
      targetPort: 8080
  type: LoadBalancer
